#ifndef ISP_UTILS_CONFIG_H
#define ISP_UTILS_CONFIG_H
#define ISP_UTILS_ENABLE_cpu_386 1
#define ISP_UTILS_ENABLE_cpu_8086 1
#define ISP_UTILS_ENABLE_dos16r 1
#define ISP_UTILS_ENABLE_dos32p 1
#define ISP_UTILS_ENABLE_linux_host 1
#define ISP_UTILS_ENABLE_mm_compact 1
#define ISP_UTILS_ENABLE_mm_flat 1
#define ISP_UTILS_ENABLE_mm_large 1
#define ISP_UTILS_ENABLE_mm_medium 1
#define ISP_UTILS_ENABLE_mm_small 1
#define ISP_UTILS_ENABLE_win16b 1
#define ISP_UTILS_ENABLE_win16p 1
#define ISP_UTILS_ENABLE_win16r 1
#define ISP_UTILS_ENABLE_win32 1
#define ISP_UTILS_ENABLE_win32s 1
#define ISP_UTILS_ENABLE_win386 1
#define ISP_UTILS_ENABLE_windows_30 1
#define ISP_UTILS_ENABLE_windows_31 1
#define ISP_UTILS_ENABLE_windows_95 1
#define ISP_UTILS_ENABLE_windows_nt 1
#define ISP_UTILS_HAVE_FCNTL_H 1
#define ISP_UTILS_HAVE_INTTYPES_H 1
#define ISP_UTILS_HAVE_MALLOC 1
#define ISP_UTILS_HAVE_MEMORY_H 1
#define ISP_UTILS_HAVE_MEMSET 1
#define ISP_UTILS_HAVE_STDINT_H 1
#define ISP_UTILS_HAVE_STDLIB_H 1
#define ISP_UTILS_HAVE_STRINGS_H 1
#define ISP_UTILS_HAVE_STRING_H 1
#define ISP_UTILS_HAVE_SYS_SOCKET_H 1
#define ISP_UTILS_HAVE_SYS_STAT_H 1
#define ISP_UTILS_HAVE_SYS_TYPES_H 1
#define ISP_UTILS_HAVE_UNISTD_H 1
#endif
