#!/bin/bash
./cleantree
./autogen.sh
x=`uname -m`
LIB=

if [ x"$x" == x"x86_64" ]; then LIB="--libdir=/usr/lib64"; fi
./configure --prefix=/usr --disable-debug --disable-cpuonly --disable-extlib --disable-mm-compact --disable-mm-small --disable-mm-medium --disable-mm-large --disable-mm-huge --disable-mm-flat --disable-dos16r --disable-dos32p --disable-win16r --disable-win16p --disable-win16b --disable-win386 --disable-win32s --disable-win32 --disable-linux-host --disable-cpu-8086 --disable-cpu-286 --disable-cpu-386 --disable-cpu-486 --disable-cpu-586 --enable-cpu-686 --disable-windows-nt --disable-windows-me --disable-windows-98 --disable-windows-95 --disable-windows-31 --disable-windows-30 --disable-windows-20 --disable-windows-10 --enable-efi-ia32 --enable-efi-x64 $LIB || exit 1

