# This is a separate makefile because GNU automake interferes with GNU make conditionals
ifdef target_subdir

all-targets-abs-dirs: $(abs_exe_dir) $(abs_lib_dir) $(abs_obj_dir)

all-targets: all-targets-abs-dirs

endif

