# This is a separate makefile because GNU automake interferes with GNU make conditionals
ifdef target_subdir

all-targets-abs-dirs: $(abs_exe_dir) $(abs_lib_dir) $(abs_obj_dir)

all-programs: $(abs_exe_dir)/test1$(exe_suffix)

# TODO move to own library
ifeq ($(TARGET_WINDOWS_WIN32s),1)
lib_win32s_compat=$(abs_lib_dir)/compat$(lib_suffix)
obj_win32s_compat=$(abs_obj_dir)/compat$(obj_suffix)

$(lib_win32s_compat): $(obj_win32s_compat)
	$(WLIB) -q -b -c $@ $(foreach x,$^,-+$(x))

$(obj_win32s_compat): compat.c
 ifeq ($(target_subdir),linux/host)
	$(CC) $(CFLAGS) -I.. -I../.. -c -o $@ $^
 else
	$(WCC) $(WCCFLAGS) -fo=$(abs_obj_dir)/.obj -i=.. -i=../.. $^
 endif
endif
# end TODO

$(abs_exe_dir)/test1$(exe_suffix): $(obj_win32s_compat) $(abs_obj_dir)/test1$(obj_suffix)
ifeq ($(target_subdir),linux/host)
	$(CC) $(LDFLAGS) -o $@ $^
else
	@echo option quiet system $(WLINK_SYSTEM) $(WLINKFLAGS) $(WLINK_SEGMENTS) $(foreach x,$(filter %$(obj_suffix),$^),file "$(x)") option map=$(abs_obj_dir)/test1.map name $@ >$(abs_obj_dir)/test1.cmd
	$(WLINK) @$(abs_obj_dir)/test1.cmd
	@rm -f $(abs_obj_dir)/test1.cmd
 ifeq ($(TARGET_WINDOWS_WIN386),1)
	@$(WIN386_EXE_TO_REX_IF_REX) $@
	@$(WBIND) $@ -q -n
 endif
 ifneq ($(WIN16_NE_SETVER),)
	$(WIN16_NE_SETVER) $@
 endif
endif

$(abs_obj_dir)/test1$(obj_suffix): test1.c
ifeq ($(target_subdir),linux/host)
	$(CC) $(CFLAGS) -I.. -I../.. -c -o $@ $^
else
	$(WCC) $(WCCFLAGS) -fo=$(abs_obj_dir)/.obj -i=.. -i=../.. $^
endif

all-targets: all-targets-abs-dirs all-programs
	@true

clean-targets:
	@rm -Rfv $(abs_exe_dir) $(abs_lib_dir) $(abs_obj_dir)

endif

