
lib_hw_cpu_libcpu=$(abs_top_srcdir)/build/hw/cpu/$(target_subdir)/lib/libcpu$(lib_suffix)
lib_hw_cpu_libcpu_wlink=library $(lib_hw_cpu_libcpu)
lib_hw_cpu_libcpu_dependencies=

ifneq ($(lib_hw_cpu_libcpu),)
$(lib_hw_cpu_libcpu):
	$(MAKE) -C $(abs_top_srcdir)/hw/cpu --no-print-directory -$(MAKEFLAGS) all-targets
endif

